import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Layout from './layout'

import cookie from 'cookie-cutter'


export default function Home() {

  const handleClick =(e) =>{
    e.preventDefault();
    e.stopPropagation();
    const url = e.target.href;
    const rtClickid = cookie.get('rtkclickid-store')

    console.log('HANDLE CLICK',url)
    console.log('CLICK ID: ', rtClickid)

    window.open(`${url}?clickid=${rtClickid}`)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Category - Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Test PAGE</a>
        </h1>

        <p className={styles.description}>
          <Link prefetch={false} href="/"><a> Home</a></Link><br />
          <Link prefetch={false} href="/search"><a> Search Page</a></Link> <br />
          <Link prefetch={false} href="/category"><a> Category Page</a></Link> <br />
          <Link prefetch={false} href="/test"><a> Test Page</a></Link> <br />
      
        </p>

        <div style={{
          display: 'flex', 
          flex: 1,
          width: 500,
          justifyContent: 'space-between',
          }} className="offer-links">

          <div><a onClick={handleClick} href="https://truely.rdtk.io/click/7">Offer 7</a></div>
          <div><a onClick={handleClick} href="https://truely.rdtk.io/click/8">Offer 8</a></div>
          <div><a onClick={handleClick} href="https://truely.rdtk.io/click/9">Offer 9</a></div>
          <div><a onClick={handleClick} href="https://truely.rdtk.io/click/10">Offer 10</a></div>
        </div>

      </Layout>
    </div>
  )
}
